### ISSUE TITLE
Installing via requirements.yml not possible?

### ISSUE THREAD

**Issue by synergiator** [zauberpony/ansible-mysql-query#34]
What needs to be put to ```requirements.yml``` to install this module as alternative to console?

* ansible-galaxy [core 2.11.3]
* Ubuntu 20.04 / Python 3.8.10
* error: ```ERROR! Neither the collection requirement entry key 'name', nor 'source' point to a concrete resolvable collection artifact. Also 'name' is not an FQCN. A valid collection name must be in the format <namespace>.<collection>. Please make sure that the namespace and the collection name  contain characters from [a-zA-Z0-9_] only.```

```yaml
---
collections:
  - name:  zauberpony.mysql-query
    version: 0.6.1
```
