### ISSUE TITLE
Use MySQL functions?

### ISSUE THREAD

**Issue by washek** [zauberpony/ansible-mysql-query#4]
Hi,

first of all, thank you for sharing your work. I would like to use your ansible role for setting/changing passwords in my database, so I need to use mysql functions like PASSWORD().

Currently is the value stored as plaintext (passwd: PASSWORD('blabla') is inserted as "PASSWORD('blabla')", not "*xxxxxxxxx"). So problably are values escaped somehow.

Is there an option to disable it? I was not able to found it.
Thanks!

**Comment by zauberpony** [comment]
Hi,

The query built by the module looks like `insert into users (name, passwd) values (%s, %s)`, then mysqldb's `cursor.execute` gets the query and a list of parameters, e.g. ("john", "PASSWORD('bla')"), thus it's cursor.execute that does the escaping.

I'm not sure if it's a good idea to circumvent this escaping always by building the query string with the values directly put it. 
I'm thinking about an extended syntax like:

```
…values:
      name: john
      passwd:
        function: PASSWORD
        value: bla
```

So, if you want to use MySQL functions you do not pass a string as value, but a dictionary with the function name and the value (or even values?) given to the function.

What do you think about that?

**Comment by washek** [comment]
Your proposed extensions looks great, it would definitely solve the problem. I think that it's better than disabling escaping globally. It would be great if you had time to modify your script.

**Comment by zauberpony** [comment]
Hey @washek 

Sorry for the delay. But I finally added the feature in a seperate [branch](https://github.com/zauberpony/ansible-mysql-query/tree/support-mysql-functions).

Unfortunately, due to api-changes in ansible 2.0 my previous test-setup doesn't work anymore, thus adding the feature was more a trial-and-error experience, and the module has not been tested as good as before. BUT: I'm confident that I didn't introduce grave regressions ;)

Would you mind to test the changes (just download the *mysql_query* file from the feature-branch and put it into */library*)?

In the meantime I will clean up the outdated tests, check if the documentation is up-to-date etc, and if the changes work out for you, I would release a new version.

Oh, btw, opposed to my previous proposal I changed the arguments for functions. You MUST set a placeholder ('%s') in the function where the 'value' should be inserted. Reason behind this: you might want to use functions with additional arguments, e.g.:

```
…values:
      name: john
      remainder:
        function: MOD(%s, 16)
        value: 29
```

(Yeah, silly example, but you get the point). In the 'password' case you would write:
```
…values:
      name: john
      passwd:
        function: PASSWORD(%s)
        value: "passw0rd"
```
